version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - my_net
    restart: always

  ps_adminer:
    container_name: ps_adminer
    image: adminer
    ports:
      - "8080:8080"
    # env_file: 
    #   - .env
    networks:
      - my_net
    restart: always
  
  nest_js:
    container_name: nest_js
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - my_net

  vite_js:
    container_name: vite_js
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - nest_js
    networks:
      - my_net

networks:
  my_net:
    driver: bridge

    
